language: ruby
sudo: false
rvm: 2.3.3
cache:
  bundler: true
install:
  - cd spec/dummy-rails4 && bundle install
  - cd ../dummy-rails5 && bundle install
script:
  - echo $(pwd)
  - cd ../dummy-rails4 && bundle exec rspec spec/
  - echo $(pwd)
  - cd ../dummy-rails5 && bundle exec rspec spec/
notifications:
  email: false
