default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dummy_rails4_development

test:
  <<: *default
  database: dummy_raills4_test

production:
  <<: *default
  database: dummy_rails4_production
  username: dummy
  password: <%= ENV['DUMMY_DATABASE_PASSWORD'] %>
