# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 139e319331a8e4bd3360b80628597ca68de76c23732fb2ff32b8dfddf0e31b70ae8d5e98b92ac44cc2d5962060110d1684df0eaaa2212e227e7f05280d668cd6

test:
  secret_key_base: af4f922cc881ac4c33351ae16b511e608844c692114782fb6af22391fbd89eb51d0f8c7e3b52fd948e5925ff33ab2ffa6b9cac3657618b6c7ab5365f673072b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
